namespace Genesis.Shared.Constant
{
    public enum ObjectType
    {
        Object = 1,
        //ObjectGraphics = 1,
        ObjectGraphicsPhysics = 3,
        QuestObject = 4,
        Item = 6,
        Gadget = 8,
        PowerPlant = 10,
        Weapon = 12,
        Vehicle = 14,
        WheelSet = 16,
        Creature = 18,
        Character = 20,
        Store = 22,
        Bullet = 24,
        Commodity = 26,
        Armor = 28,
        EnterPoint = 30,
        ExitPoint = 32,
        ContinentObject = 34,
        Town = 36,
        Encounter = 38,
        CharacterBody = 40,
        CharacterHead = 42,
        CharacterHair = 44,
        CharacterAccessory = 46,
        Convoy = 48,
        TinkeringKit = 50,
        Accessory = 52,
        SpawnPoint = 54,
        Trigger = 56,
        Reaction = 58,
        MapModulePlacement = 60,
        MapPath = 62,
        MissionObject = 64,
        Money = 66,
        Ornament = 68,
        RaceItem = 70,
        Outpost = 72
    }
}
